### PR TITLE
Remove styling

### PR DESCRIPTION
**Pull request by flying-sheep**
Users like to be able to select their own styles and themes.

I would never use something that diverges noticably from my system look&feel

### CODE REVIEW

**Comment by ghost** [comment]
Thanks, we will work on more easy styling on the future... :smile_cat: mainly for non-Qt DEs.

**Comment by flying-sheep** [comment]
thank you! maybe a command line argument or environment variable will be the right approach.

and e.g. on OSX the visual style is already known, so we can detect if running there and apply a style sheet specific for OSX

**Comment by ghost** [comment]
@flying-sheep I am thinking something like using `~/.unicodemoticons.css` with a Style Sheet for Theming.
- If no `~/.unicodemoticons.css` file, write a basic default style sheet.
- If `~/.unicodemoticons.css` file, read style sheet from there and apply it.
- Add new Option `Set UI Style` allows to Edit that `~/.unicodemoticons.css` file.
- The `~/.unicodemoticons.css` opens with your favorite IDE/Editor/WYSIWYG-Editor.

Some friendly access for the CSS is needed anyway, on old GTK Desktops Qt5 by default looks ugly.

:smiley:

**Comment by flying-sheep** [comment]
make that `$XDG_CONFIG_HOME/unicodemoticons/style.css` or so and i’m all for it.

[look here](http://pyxdg.readthedocs.org/en/latest/basedirectory.html#configuration-directories):

``` python
from pathlib import Path
import xdg

config_path = Path(xdg.BaseDirectory.save_config_path('unicodemoticons'))
css_path = config_path / 'style.css'

with css_path.open() as css_f:
    try:
        css = css_f.read()
    except IOError:
        css = None

if css == None:
    css = DEFAULT_CSS
    with css_path.open('w') as css_f:
        css_f.write(css)
```

**Comment by ghost** [comment]
@flying-sheep I dont like `style.css` is obvious is the style, its like say `javascript.js`.
I think `unicodemoticon.css` is good, and why a folder if its a single file :grey_question: 
_(We will use folder if we need multiple files, but its not the use case right now)_

On Linux I dont have any `$XDG_CONFIG_HOME`, 
I have `$XDG_CONFIG_DIRS` but those are root only and contains a list.

I am using the following, is more or less crossplatform:
`style_file = os.path.join(os.path.expanduser("~"), ".unicodemoticon.css")`

On Linux its `/home/user/.unicodemoticon.css`, always hidden file,
on Os X should be `/Users/user/.unicodemoticons.css` I dont have Mac anyways,
on Windows, well...   it do not even support Unicode properly.

I dont have problem with `pathlib` since is Std Lib BuiltIn on Python3, 
but I want to avoid being tied to third party `xdg` as much as possible.

The full function I am using right now and testing locally is:

``` python
def set_or_get_stylesheet(self, stylesheet=QSS_STYLE):
    style_file = os.path.join(os.path.expanduser("~"), ".unicodemoticon.css")
    if not os.path.isfile(style_file):
        with open(style_file, "w", encoding="utf-8") as style_file_object:
            style_file_object.write(stylesheet.strip())
    with open(style_file, "r", encoding="utf-8") as style_file_object:
        stylesheet = style_file_object.read().strip()
    return stylesheet
```

Thanks for Collaboration on this; Let me know what you think...
:smile:

**Comment by flying-sheep** [comment]
> On Linux I dont have any `$XDG_CONFIG_HOME`

the spec says that it’s `~/.config` if the `$XDG_CONFIG_HOME` variable is not set.

and the spec is there in order to eliminate all the junk in `~`:

``` console
$ ls .* | wc -l
1122
```

i’d love if you didn’t add to it and respect the XDG spec.

it’s also really easy to implement yourself if you don’t want to depend on pyxdg:

``` python
config_path = os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
```

> We will use folder if we need multiple files, but its not the use case right now

yeah, that was my motivation: we can also store a config file in there. and then it’s either `.config/unicodemoticon/unicodemoticon.{css,js}` or `.config/unicodemoticon/{style.css,config.cfg}` (or something else?)

**Comment by flying-sheep** [comment]
oh, and to also ideally support other OSs:

``` python
if sys.platform.startswith('darwin'):
    config_path = os.path.expanduser(`~/Library/Preferences`)
else if sys.platform.startswith('win32'):
    config_path = os.getenv('APPDATA')
else:
    config_path = os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
```

**Comment by ghost** [comment]
Ok, will try to use that snippet this weekend, we are at ~ **7.777 Downloads / Month** on UnicodEmoticons.
- https://twitter.com/juancarlospaco/status/604447602994753536

# d-( ʘ‿ʘ )_m

**Pull request merged**
