### PR TITLE
split up everything and removed duplicated functionality

### PR DESCRIPTION
**Pull request by flying-sheep**
this is too big for single file, and hacking around it with “stealth strings” and eval is just evil.

### CODE REVIEW

**Comment by ghost** [comment]
Named Tuple uses eval on Std Lib for example, you are using it anyways.

Bottle uses Single-File and is the key to its successfulness http://bottlepy.org
https://github.com/bottlepy/bottle/blob/master/bottle.py

**Comment by flying-sheep** [comment]
> Where is elsewhere

on the [AUR of course](https://aur.archlinux.org/cgit/aur.git/tree/?h=unicodemoticon)

> Bottle uses Single-File and is the key to its successfulness

sorry, i just don’t think this is maintainable at all using your stealth strings.
- hard to fix bugs (decode, change code, encode, insert, check if bug fixed, goto 1)
- inserts stuff into the global namespace invisibly

either we create a lib containing all the external util stuff and make this depend on that lib or we split it into multiple files. i don’t see another reasonable alternative

**Comment by ghost** [comment]
No, the idea is to use it as a boilerplate, of code thats agnostic of the functionalities of the main app itself,
bootstrap a basic functionality that you will need anyways, like a nice logger, etc.

No matter what, you will need to contruct a Logger all apps repeat that in different ways,
I try to improve by making best code posible and pluggable anywhere directly.

I need that because the same code was repeated again, again and again on all my other apps:
https://github.com/juancarlospaco/dookumentation/blob/master/dookumentation.py#L645
https://github.com/juancarlospaco/css-html-js-minify/blob/7b2210a8596b0cdae24239f7bc2b3e65242af9fb/css-html-js-minify.py#L1216
https://github.com/juancarlospaco/css-html-prettify/blob/74421a3354707410505bb58fb5407c0ceadb9d7d/css-html-prettify.py#L600
. . . and so on  . . .

Improvements over that boilerplate will be replicated all over the other apps.
Its something you can just literally copy-paste to any script and call functions right away.

I research other third party already done solutions like Boltons but dont add too much value, dont even provide a basic Log file https://boltons.readthedocs.org

---

Think the following:
- No code of Unicodemoticon itself will be ever as stealth strings, never never.
- For example Requests is copied embedded inside PIP, and no one ever complain about that.
- I found >20 implementations of a command line progress bar inside different apps.
- NodeJS uses Minified code on itself too and no one ever complained about that. ¯|_(ツ)/¯

**Comment by flying-sheep** [comment]
then simply publish the contents of the `utils` file i extracted (the contents of your stealth string) to pypi and add it as dependency. call it “jutilian” or so 😉

this way stuff will never get out of sync. you don’t have the hassle of maintaining changes, …

and as you can see you already duplicated two of the functions to setup.py. code duplication is bad! as well as duplicated imports, stuff that ends up in the global namespace, …

**Comment by ghost** [comment]
Setup.py needs a clean up, also code is old, I invented stealth string after.

But I dont want to create Boltons2. End-Users dont care anyway.

As I said, Requests is embedded inside PIP, no one complains. PIP dont depend on Requests.

I will take care of all the stuff inside stealth strings boilerplate, is just an extra line, provides awesome,
the code of the app itself is the visible relevant part... we need a whole world of stuff that End-Users care like Screenshots, MacOsX Testing, Video Screenscast, Manual, etc etc etc

Apps with lots of dependencies are also bad, makes me remember of PIL depends on lots of stuff, some dont even PIP-installables, things break even worse.

No Donation at all, not even BitCoin has been ever done...,
so I will try to manage in a way that allows the project to be alive.

**Comment by flying-sheep** [comment]
OK, so you think it will be more popular if it’s one file? [why not a zipapp then](https://docs.python.org/3/library/zipapp.html)?

**Comment by ghost** [comment]
Maybe I can create a Repo, with the code of the boilerplate, and Scripts to pack it as zipapp and stealth string but embed not as module like boltons...

**Comment by ghost** [comment]
Zipapp makes 100% of the code not readable by humans, 
stealth string only hides the repetitive app-agnostic part, 
but I am Ok with zipapp as an alternative too.

**Comment by flying-sheep** [comment]
> Zipapp makes 100% of the code not readable by humans, 

just open or extract it as .zip file:

spectacle h21322

creating it is literally `python -m zipapp unicodemoticon`, and you start it by clicking the `.pyz`.

so can i merge this and then
1. we attach zipapps to our [releases](https://github.com/juancarlospaco/unicodemoticon/releases)
2. i modify the [Try it](https://github.com/juancarlospaco/unicodemoticon#try-it-) readme section to work with a zipapp

?

**Comment by ghost** [comment]
As I was saying, I also like Pythons zipapp :+1:

**Comment by flying-sheep** [comment]
OK, great!

**Comment by ghost** [comment]
Not sure if I agree with this merge, but whatever ¯|_(ツ)/¯

**Comment by flying-sheep** [comment]
oh damn, i interpreted your “I also like Pythons zipapp :+1:” that way!

sorry!

**Comment by flying-sheep** [comment]
what do you want me to fix up?

PS: how do you create those .rpm and .deb files? i’m on arch, so no `rpm` or `apt` available…

**Comment by ghost** [comment]
Install them, hehe, its on AUR I think, setup.py file has instructions and commands to build them both.
https://github.com/juancarlospaco/unicodemoticon/blob/master/setup.py#L5
https://aur.archlinux.org/packages/rpm-org/
https://aur.archlinux.org/packages/dpkg/
Try on a VM VirtualBox if you dont want to install them. I also have an Arch (Antergos) on the other computer.
:smile_cat:

**Comment by flying-sheep** [comment]
ok, will build and attach to the release.

see, i removed the .deb/.rpm packages from the repo (git doesn’t like binaries too much) and attached them to the [2.0.0 release](https://github.com/juancarlospaco/unicodemoticon/releases/tag/2.0.0). i made the README point to the `.pyz` and will add links to the packages, too.

**Comment by ghost** [comment]
Yeah, I think the more options the better...

**Comment by flying-sheep** [comment]
damn nothing works :sob: 
- rpm: `Error while building the RPM: Cannot open package database in /var/lib/rpm`
- deb: `dpkg-query: No package found fitting debhelper ERROR running: /usr/bin/dpkg-query --show --showformat=${Version} debhelper`

**Comment by flying-sheep** [comment]
i can do the VMs if you don’t want to create the packages, but you’ll have to upload to PyPI as it’s posted under your account there.

i’ll update the PKGBUILD once 2.1.0 is on PyPI

**Comment by ghost** [comment]
Report on AUR, I dunno, maybe is something to use on a Docker or similar I dont know.

I prefer to release to PyPI when theres something new for end user, right now is just the same but split, for end user thats no difference.

**Comment by flying-sheep** [comment]
hmm, at least we have the quit menu entry which helped me quite good, but sure!

and then i won’t have to look into the RPM/DEB stuff right now because it’s not a “real” release :wink:

**Comment by ghost** [comment]
We should have made this a bug, like a road map discussion... 
Take it easy no hurry, I was reading that pkgbuild supports SHA instead of MD5(broken).

**Comment by flying-sheep** [comment]
i wouldn’t worry too much. i doubt anyone uses unicodemoticon’s PyPI version as attack vector :wink: 

but if you want i can of course change it to use SHA256

**Comment by ghost** [comment]
@flying-sheep https://github.com/juancarlospaco/boilerplatembed#boilerplatembed

**Comment by ghost** [comment]
@flying-sheep I can also make you owner of the PyPi, but I dont know your user there, you must have user to be admin, I try `flying-sheep` but it says user dont exist... so you can release to PyPi too...

**Comment by flying-sheep** [comment]
i’m `flyingsheep` there :blush:

**Comment by ghost** [comment]
Done.

**Pull request merged**
